configName: sam_l22_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAML22N18A
projectName: ''
settings:
  PackageFilter: audio;bootloader;bsp;core;core_apps_pic32cz_ca;crypto;cryptoauthlib;csp;gfx;mbed_os_rtos;mbed_os_rtos_apps;micrium_ucos3;motor_control;net;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: ALL
  DFPPath: .\dev_packs\Microchip\SAML22_DFP\3.5.68\atdf\ATSAML22N18A.atdf
